### ISSUE TITLE
Fails to build in HassOS KVM, unable to find package

### ISSUE THREAD

**Issue by DavidMSCode** [mr-ransel/addon-nebula#3]
I was able to fix this by making some changes to the Dockerfile but here are the specifics of the error first.

Running HassOS in a KVM on Ubuntu 22.04. After following the directions for manual installation and clicking "install" in the Add-Ons store I get this popup:

> The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r3         git=2.36.4-r0         && apk add --no-cache         go=1.18.7-r0         iptables=1.8.8-r1         && git clone --branch "v1.6.0" --depth=1         "https://github.com/slackhq/nebula.git" /tmp/nebula         && cd /tmp/nebula     && make bin     && mv nebula /usr/bin/nebula     && mv nebula-cert /usr/bin/nebula-cert         && rm -f -r /tmp/*     && apk del --no-cache --purge         .build-dependencies         go' returned a non-zero code: 2

Checking the end of journalctl on the host I found this relevant log:
>Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 23-04-21 17:32:54 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build local/amd64-addon-nebula:dev: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r3         git=2.36.4-r0         && apk add --no-cache         go=1.18.7-r0         iptables=1.8.8-r1         && git clone --branch "v1.6.0" --depth=1         "https://github.com/slackhq/nebula.git" /tmp/nebula         && cd /tmp/nebula     && make bin     && mv nebula /usr/bin/nebula     && mv nebula-cert /usr/bin/nebula-cert         && rm -f -r /tmp/*     && apk del --no-cache --purge         .build-dependencies         go' returned a non-zerocode: 2
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 23-04-21 17:32:54 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: Step 1/11 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/aarch64:12.2.7
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: Step 2/11 : FROM ${BUILD_FROM}
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:  ---> d72163b17d95
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: Step 3/11 : SHELL ["/bin/b
ash", "-o", "pipefail", "-c"]
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:  ---> Using cache
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:  ---> 0fe22c737323
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: Step 4/11 : RUN     apk add --no-cache --virtual .build-dependencies         build-base=0.5-r3         git=2.36.4-r0         && apk add --no-cache         go=1.18.7-r0         iptables=1.8.8-r1         && git clone --branch"v1.6.0" --depth=1         "https://github.com/slackhq/nebula.git" /tmp/nebula         && cd /tmp/nebula     && make bin     && mv nebula /usr/bin/nebula     && mv nebula-cert /usr/bin/nebula-cert         && rm -f -r /tmp/*     && apk del --no-cache --purge         .build-dependencies         go
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:  ---> Running in 188da5dbfd9c
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: ERROR: unable to select packages:
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:   git-2.36.5-r0:
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:     breaks: .build-dependencies-20230421.223253[git=2.36.4-r0]
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:   .build-dependencies-20230421.223253:
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:     masked in: cache
Apr 21 22:32:54 homeassistant hassio_supervisor[448]:     satisfies: world[.build-dependencies=20230421.223253]
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: Removing intermediate container 188da5dbfd9c
Apr 21 22:32:54 homeassistant hassio_supervisor[448]: 
Apr 21 22:32:54 homeassistant homeassistant[448]: 2023-04-21 17:32:54.167 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/local_nebula/install - The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r3         git=2.36.4-r0         && apk add --no-cache         go=1.18.7-r0         iptables=1.8.8-r1         && git clone --branch "v1.6.0" --depth=1         "https://github.com/slackhq/nebula.git" /tmp/nebula         && cd /tmp/nebula     && make bin     && mv nebula /usr/bin/nebula     && mv nebula-cert /usr/bin/nebula-cert         && rm -f -r /tmp/*     && apk del --no-cache --purge         .build-dependencies         go' returned a non-zero code: 2

Seems APK is unable to find that version of git. So I added a run line above the install nebula line in Dockerfile to update && upgrade repos then add git (no specified version)
then I remove the version specification for git in Build Nebula section

```ARG BUILD_FROM=ghcr.io/hassio-addons/base/aarch64:12.2.7

FROM ${BUILD_FROM}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# update the repositories
RUN apk update && apk upgrade && apk add git

# Build Nebula
RUN \
    apk add --no-cache --virtual .build-dependencies \
        build-base=0.5-r3 \
    \
    && apk add --no-cache \
        go=1.18.7-r0 \
        iptables=1.8.8-r1 \
#        libqrencode=4.1.1-r0 \
#        openresolv=3.12.0-r0 \
#        wireguard-tools=1.0.20210914-r0 \
    \
    && git clone --branch "v1.6.0" --depth=1 \
        "https://github.com/slackhq/nebula.git" /tmp/nebula \
    \
    && cd /tmp/nebula \
    && make bin \
    && mv nebula /usr/bin/nebula \
    && mv nebula-cert /usr/bin/nebula-cert \
#    && chmod +x /usr/bin/nebula \
#    && chmod +x /usr/bin/nebula-cert \
    \
    && rm -f -r /tmp/* \
    && apk del --no-cache --purge \
        .build-dependencies \
        go

COPY rootfs /
```

**Comment by mr-ransel** [comment]
Hi! I pushed a pretty substantial update today and updated the configuration and a lot of the packages, as well as the base images. Want to try again and see if it's building properly for you?

**Comment by d4l3k** [comment]
@mr-ransel I just pulled and seem to be hitting the same issue:

```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  45.57kB
Step 1/5 : ARG BUILD_FROM=ghcr.io/hassio-addons/base:14.1.0
Step 2/5 : FROM ${BUILD_FROM}
14.1.0: Pulling from hassio-addons/base
7264a8db6415: Pull complete
fd9bf82a4734: Pull complete
27e17571d57a: Pull complete
b2a5a3ba600e: Pull complete
Digest: sha256:8b43f7ceac0ffb499107c3412a72e57c417c36725b1762279af1b66993668236
Status: Downloaded newer image for ghcr.io/hassio-addons/base:14.1.0
 ---> 04f18ed3e104
Step 3/5 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Running in 1b7b9ebcee65
Removing intermediate container 1b7b9ebcee65
 ---> a86e7e2c74df
Step 4/5 : RUN     apk add --no-cache --virtual .build-dependencies         build-base=0.5-r3         git=2.40.1-r0         && apk add --no-cache         go         iptables         yq         bind-tools         && git clone --branch "v1.7.2" --depth=1         "https://github.com/slackhq/nebula.git" /tmp/nebula         && cd /tmp/nebula     && make bin     && mv nebula /usr/bin/nebula     && mv nebula-cert /usr/bin/nebula-cert         && rm -f -r /tmp/*     && apk del --no-cache --purge         .build-dependencies         go
 ---> Running in 0a73cd912799
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  musl-1.2.4-r1:
    breaks: musl-dev-1.2.4-r2[musl=1.2.4-r2]
    satisfies: world[musl=1.2.4-r1]
               apk-tools-2.14.0-r2[musl>=1.2.3_git20230424]
               apk-tools-2.14.0-r2[so:libc.musl-x86_64.so.1]
               isl26-0.26-r1[so:libc.musl-x86_64.so.1]
               dash-0.5.12-r2[so:libc.musl-x86_64.so.1]
               gcc-12.2.1_git20220924-r10[so:libc.musl-x86_64.so.1]
               g++-12.2.1_git20220924-r10[so:libc.musl-x86_64.so.1]
               patch-2.7.6-r10[so:libc.musl-x86_64.so.1]
               bash-5.2.15-r5[so:libc.musl-x86_64.so.1]
               ca-certificates-20230506-r0[so:libc.musl-x86_64.so.1]
               binutils-2.40-r7[so:libc.musl-x86_64.so.1]
               busybox-1.36.1-r2[so:libc.musl-x86_64.so.1]
               curl-8.2.1-r0[so:libc.musl-x86_64.so.1]
               git-2.40.1-r0[so:libc.musl-x86_64.so.1]
               musl-utils-1.2.4-r1[so:libc.musl-x86_64.so.1]
               nghttp2-libs-1.55.1-r0[so:libc.musl-x86_64.so.1]
               libstdc++-12.2.1_git20220924-r10[so:libc.musl-x86_64.so.1]
               brotli-libs-1.0.9-r14[so:libc.musl-x86_64.so.1]
               file-5.45-r0[so:libc.musl-x86_64.so.1]
               libcurl-8.2.1-r0[so:libc.musl-x86_64.so.1]
               mpc1-1.3.1-r1[so:libc.musl-x86_64.so.1]
               libmagic-5.45-r0[so:libc.musl-x86_64.so.1]
               oniguruma-6.9.8-r1[so:libc.musl-x86_64.so.1]
               mpfr4-4.2.0_p12-r0[so:libc.musl-x86_64.so.1]
               libcrypto3-3.1.2-r0[so:libc.musl-x86_64.so.1]
               zlib-1.2.13-r1[so:libc.musl-x86_64.so.1]
               libgomp-12.2.1_git20220924-r10[so:libc.musl-x86_64.so.1]
               readline-8.2.1-r1[so:libc.musl-x86_64.so.1]
               make-4.4.1-r1[so:libc.musl-x86_64.so.1]
               zstd-libs-1.5.5-r4[so:libc.musl-x86_64.so.1]
               libgcc-12.2.1_git20220924-r10[so:libc.musl-x86_64.so.1]
               libssl3-3.1.2-r0[so:libc.musl-x86_64.so.1]
               libexpat-2.5.0-r1[so:libc.musl-x86_64.so.1]
               libatomic-12.2.1_git20220924-r10[so:libc.musl-x86_64.so.1]
               libidn2-2.3.4-r1[so:libc.musl-x86_64.so.1]
               pcre2-10.42-r1[so:libc.musl-x86_64.so.1]
               scanelf-1.3.7-r1[so:libc.musl-x86_64.so.1]
               gmp-6.2.1-r3[so:libc.musl-x86_64.so.1]
               jq-1.6-r3[so:libc.musl-x86_64.so.1]
               libncursesw-6.4_p20230506-r0[so:libc.musl-x86_64.so.1]
               libunistring-1.1-r1[so:libc.musl-x86_64.so.1]
  .build-dependencies-20231123.223710:
    masked in: cache
    satisfies: world[.build-dependencies=20231123.223710]
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r3         git=2.40.1-r0         && apk add --no-cache         go         iptables         yq         bind-tools         && git clone --branch "v1.7.2" --depth=1         "https://github.com/slackhq/nebula.git" /tmp/nebula         && cd /tmp/nebula     && make bin     && mv nebula /usr/bin/nebula     && mv nebula-cert /usr/bin/nebula-cert         && rm -f -r /tmp/*     && apk del --no-cache --purge         .build-dependencies         go' returned a non-zero code: 48
```
